### ISSUE TITLE
Coauthor names in publications should be links

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#109]
This should trigger a search for the researcher (if not yet known) or redirect to their page (if known).

**Comment by wetneb** [comment]
Actually, there is a problem with that: any search engine will trigger a huge amount of paper-fetching jobs by folowing these links, and dissemin will die :-(
I think we need to keep that feature behind a form I'm afraid.

Maybe we could simply add this form in the top bar so that it's easier to look up new researchers without having to go back to the homepage.

**Comment by a3nm** [comment]
For well-behaved search engines, you can just put them in nofollow.

Search engines may not be well-behaved, though, but in this case it would be better to have the names look like links, while clicking them could trigger a POST request or Javascript processing (which the bad bots won't do).

**Comment by wetneb** [comment]
OK, we have to try that. Being able to browse by jumping from co-author to co-author would be great indeed.

**Comment by p4bl0-** [comment]
I don't think having links on each is a good idea. In intutional instances we don't want to create pages for each co-authors of papers as most of these researcher won't be affiliated with the institution. So IMO it makes sense to have only links on names which are already in the database of the instance, and let people search for researchers they want to see the page of which is not that inconvenient (escpecially since the primary focus of the public ORCID based instance of Dissemin is to help researchers to deposit their own paper, not to list the publications of their colleagues, we are not here to help bibliometry).

**Comment by a3nm** [comment]
On Wed, Sep 30, 2015 at 02:54:50AM -0700, p4bl0 wrote:
> In intutional instances we don't want to create pages for each
> co-authors of papers as most of these researcher won't be affiliated
> with the institution. So IMO it makes sense to have only links on
> names which are already in the database of the instance,

OK, in institutional instances, the links should probably be restricted
to researchers from the same institution, i.e., researchers who are in
the DB.

> and let people search for researchers they want to see the page of
> which is not that inconvenient (escpecially since the primary focus of
> the public ORCID based instance of Dissemin is to help researchers to
> deposit their own paper, not to list the publications of their
> colleagues, we are not here to help bibliometry).

I don't agree. On the ORCID instance I feel it would be quite natural to
browse from researcher to researcher using links on coauthor names.

I don't get the argument about bibliometry: we already allow people to
"Look up a colleague"; if we offer this, then I guess we also want
people to access their colleague's coauthors, and I don't see how
clicking on the coauthor names wouldn't be the expected way to do it.

It's OK not to add links if we think it is technically impossible (and I
don't think it is, as long as they are not crawlable), but this is
something different from claiming that we don't want to have the links
even if we can.

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
I think in any case, if we add links to unknown authors, they will trigger the same "name disambiguation dialog" as the main page (so they will trigger javascript code, not a proper URL).
Or we can maybe avoid that if we fetch all ORCID profiles beforehand (it could be manageable).
