### ISSUE TITLE
Sort out Google indexing, add the relevant metadata as <meta> tags

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#13]
We might need to create a sitemap. This should be documented for Django.

**Comment by nemobis** [comment]
So was a sitemap created? I don't see any linked from https://dissem.in/robots.txt nor in the usual places (https://dissem.in/sitemap.xml.gz , https://dissem.in/sitemap.xml).

Having the records indexed could be a good way to get some organic recruitment from researchers who search their own name and titles and could end up on the respective records in Dissemin. (On the other hand, it could be hard to get the records displayed in search results because there are so many other websites which expose them.)

**Comment by wetneb** [comment]
No sitemap was done indeed, we could do that.

**Comment by nemobis** [comment]
Some simplistic searches seem to show that Google prefers to index our researcher profiles than individual papers. That makes sense because we may have relatively unique/different listings for each researcher (and features for them on their profile), while we don't have any unique text about papers.

So a sitemap for researcher profiles could be the first step, especially if all the ORCID profiles have been prefilled already.

**Comment by Phyks** [comment]
Related https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

which would be used whenever someone post a Dissem.in link on a social media.
