### ISSUE TITLE
Invert look up form and description

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#159]
First start with a big form, and then explain the rest

**Comment by wetneb** [comment]
![Changes to the main block](http://pintoch.ulminfo.fr/8af8e2fa7f/home.png)

Madeleine has suggested to leave more place for the form itself (for instance, http://crossref.org is clean and nice). What do you think?

**Comment by RaitoBezarius** [comment]
What about a [frosted glass effect](https://css-tricks.com/frosting-glass-css-filters/) for the form? (nothing fancy, but seem a good candidate for it).

It would emphasize the fact that the form is a call to action, I think that it's good to keep it in the center. Add some margin between the description and the Call To Action, maybe "First name" is better than "Firstname" ?

I wonder if we could just `float: left` the "Start with ORCID" button to align it with the first input.

As for the copy, "Dissemin gives freedom to your papers" as a heading?

What do you think? Sorry for the confusing thoughts!

**Comment by wetneb** [comment]
Hum, a frosted glass effect requires a non-uniform background, I think (because adding blur to a uniform background just gives you an uniform background again). So that would require adding a background as well.

About "Start with ORCID", you would align it to the left of the form, even if the form itself is centered? It feels a bit awkward to me, do you have an example of that anywhere?

**Comment by RaitoBezarius** [comment]
That's right, with adding a radial-gradient for the blue, but just a suggestion which may not be relevant.

I don't have any example right now, but "Start with ORCID" feels strange when centered because he's between "first name" and "last name", and this is an alternative to name search, so maybe it would feel better to make it start at the same position as the name search form.

If I find any similar example, I will add the references.

**Comment by wetneb** [comment]
Not relevant anymore with the new front page, where the description is shorter.
