### ISSUE TITLE
Paper categories should be explained on the right-hand side

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#164]

**Comment by wetneb** [comment]
Do we still want that now that we have the tooltips? The right bar is quite crowded now, so I'm not sure these pics would fit anywhere?

**Comment by Lysxia** [comment]
- I think we should also have a tooltip appear when we hover on the right because I don't find it obvious that there is a tooltip on each item in the result list. The tooltip gives us space to precisely describe each category, as there is still some confusion about the current single line captions (#317), mainly because they do not appear mutually exclusive.

- To make the existence of the tooltips even more obvious, we can put a (?) glyphicon next to each caption.

- Bonus points for doing it in pure CSS.

**Comment by Phyks** [comment]
For the last point, I know https://kushagragour.in/lab/hint/ which works nice.

**Comment by a3nm** [comment]
I agree, it would be nice to have tooltips when hovering on the right
over parts of the chart or over the one-line captions of the chart.

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
It looks like this has been implemented already.
