### ISSUE TITLE
ORCID profiles without names should be reported

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#190]
http://orcid.org/0000-0002-1900-3901/ does not provide any name, so we fail to identify the relevant authors in the papers.
- [x] report it to the user (with a generic message reporting pipeline, so that other PaperSources can also send messages)
- [x] use our local name as a fallback ?

**Comment by RaitoBezarius** [comment]
For the "local name", we should add a button "Use my local name as author" and reconcile the paper in our database using the fingerprints.

**Comment by RaitoBezarius** [comment]
Okay, also we need to know something really important.

First of all: do we reconcile one paper at a time? or do we reconcile all ignored papers at a time?
Then, the following question is: how to know which papers to reconcile?

We cannot ask for the frontend to pass some IDs or something like that:

### We store ignored papers in the database

Question: what do we store? Metadata? Partial paper? ORCiD ID with boolean status.

At least, we can easily make the frontend pass some kind of ID.

Security concern: if the frontend pass a random ID, and it is a good ignored paper, can he assign to himself this paper?
Solution: compute a proof that the frontend can reconcile only this paper. `proof = f(ignored_paper)`

Problem: we need to keep track of our ignored papers and purge them as soon as they "expire" (expire means: every N days where N is relatively small).
But what about attacks where a guy would create a lot of ignored papers? And would keep spamming the refresh? Well we have timeout, but every 15 minutes, we'd have to store N ignored papers.

I relatively don't know if this is a problem or not.

### We don't store ignored papers in the database

We already have the ORCiD metadata on the frontend, can't we just re-send the metadata internal identifier? And compare it to our ORCiD Profile: `ORCiDDataPaper.is_owner(researcher_sender)`

Advantages: No need to store the ignored papers, no need to purge the ignored papers.

I like the no DB support approach, at least, we can even compute a proof with it and pass it.
Less is more, right? :smile:

So you know.

My implementation is going to be the following:

- User clicks on "Use my local name as author"
- Send a request: `POST /api/papers/ignored/reconcile` with parameters `ignored_paper_identifier: 41241024810284`
- Django / DRF receives it: send a task to Celery and wait for his completion.
- Celery receives the task. Fetch the researcher, take his full name and reconcile the paper.
- Reconciling the paper is merely: take ORCiD metadata, take overrides (a `dict` where there is pre-filled metadata like `authors`)
- So we build the data paper, like we would do usually.
- If the paper is once again skipped, we raise a critical exception saying: "even after override, we could not reconcile the paper." -- the frontend should report a special error for this.
- if the paper is not skipped (:tada:), we create the bare paper, and save the bare paper in the DB (using the PaperSource primitives).
- Once, it is done, we return the true paper (DB-backed instance) to the API view.
- The API view returns it with: `{ message: 'Paper successfully reconciled.', paper: 'blablabla', merged: `true } if the true paper contains others authors than the researcher.
- If it failed, it returns `{ message: 'Paper was not successfully reconciled due to invalid metadata.', reason: 'NO_PUBDATE' }`

Once it is done, the page is refreshed and the paper is added in the list.

I don't really know what would be the best for:

- Use my local name as author for this paper.
- Use my local name as author for all ignored papers.

@wetneb What do you think?

**Comment by wetneb** [comment]
Let's not store ignored papers - we can re-fetch them via ORCID's API when the user decides to use its name as author.

About your workflow for the reconciliation, it looks very advanced. I was actually thinking about something simpler: for any ORCID paper, if all we need is an author to make it a valid paper, then just use the researcher's name (without asking), otherwise report it as a missed paper. @RaitoBezarius what would be the problems with that?

**Comment by RaitoBezarius** [comment]
@wetneb Alright, it makes sense. So basically, we should "reconcile" before the user asks for it, right? And if we cannot, it's a missed paper, right?

**Comment by wetneb** [comment]
@RaitoBezarius I think so, yes, that would be simpler for everybody, wouldn't it?

**Comment by RaitoBezarius** [comment]
@wetneb Agreed, but we should inform the user that: "you're the author because we didn't find any other authors in our sources, contact others authors to join Dissemin or update the source with a proper BibTeX?"

**Comment by wetneb** [comment]
@RaitoBezarius Haha, inviting other authors to join dissemin would be funny ^^
I think we should just let people edit the papers' metadata from dissemin, shouldn't we?

**Comment by RaitoBezarius** [comment]
@wetneb If we can confirm that this user is author of the paper, then we should let him edit the metadata.
Though the main problem is: 

> How are we going to implement papers' metadata edition?

Such feature is form intensive, right? And as we're doing a lot of refactors for now, we need to analyze how our architecture is made, how can we compose our Django apps and our JavaScript in a consistent and coherent way.
