### ISSUE TITLE
Provide a Dockerfile

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#206]
Dissemin should be available as a docker image.

**Comment by RaitoBezarius** [comment]
@wetneb Let's be more specific about what we would accomplish with a Docker image. ([just for reference](http://www.boycottdocker.org/))

**Comment by wetneb** [comment]
@RaitoBezarius oh wow, I did not know that… Well, the idea of a Dockerfile would be to make it easier for people to run dissemin on their machine, without having to run a VM, so I've heard Docker is the right solution for that. Do you have anything else to propose?

**Comment by RaitoBezarius** [comment]
@wetneb [CoreOS](https://coreos.com/) is working on a _better_ approach for containers named [rkt](https://coreos.com/rkt/), but I recall that it still a work-in-progress / not ready for production.

Don't we have already a Vagrant VM?
Do we have a list of what does it takes to run Dissemin on a machine (external dependencies -- DBs, K/V stores, etc...)?

But anyway, I would argue that: 

> Do you really need a container image to run Dissemin on your machine?

I think that we have different kinds of users:

### The user who wants to try Dissemin

#### Non-technical

He won't be able to do anything, but we can solve that by [augmenting user-friendly solutions](https://sandstorm.io/) (→ make Dissemin sandstorm compatible).

#### Technical

Grab a VM or run it through LXC / Jails / whatever he likes.

### The contributor

We can ignore this particular one as I don't know about the pain points of contributing to Dissemin for now (in terms of architecture, testing, etc...)

### The sysadmin who wants to deploy its copy of Dissemin

Do we have Ansible / Chef / any kind of deployment orchestration available?

Do we have a good file describing the deployment procedure perfectly?

Do we have easy deployments (again if we're using Vagrant) to:

* DigitalOcean
* Amazon Web Services
* Google Cloud Engine
* Rackspace
* OVH

(Put priority on production of those files -- but Vagrant / Ansible / etc... helps a lot to abstract the process).

I could miss a kind of user, for sure. But I believe that's pretty much it.

We should identify the priority of those "features" and process them one by one (probably in separate issues).

And **a remark regarding this:** While it could be really awesome to have these nice-to-have or must-have (depends on who is suffering due to the absence of those features). 

Please, remind that you'll have to maintain them if a contributor breaks something and it could be particularly hard to fix them as they require isolated experience / knowledge that is not always easy / simple to get.

So let's differentiate official and supported ways from unofficial and cool ones which could be broken / deprecated / delete / unmaintained at every moment.

But definitely, it would be incredible to give great *developer experience* and *user experience* to Dissemin's ecosystem.

**Comment by wetneb** [comment]
We don't have a Vagrant config, we have just a simple VM: http://dev.dissem.in/doc/vm.html
We also have a Travis config file that could probably be adapted to other systems:
https://github.com/dissemin/dissemin/blob/master/.travis.yml
We have some installation instructions but they're far from perfect:
http://dev.dissem.in/doc/install.html

**Comment by RaitoBezarius** [comment]
@wetneb In this case:

I suggest this course of action to help users to get Dissemin on their computer easily:

* For users: Vagrant (based on VirtualBox or VMWare or Hyper-V) can run Dissemin just with a simple: `vagrant up`
* To provision our Vagrant, we can do an [Ansible](docs.ansible.com/ansible/playbooks.html) playbook, it will enable us to be able to deploy Dissemin to Vagrant, DigitalOcean, AWS, etc...
* Finally, for our test infrastructure, Travis is indeed a good idea.

So:

* Let's write an Ansible playbook to install Dissemin's dependencies, populate config files, and deploy Dissemin by using the Travis config file.
* Let's write a Vagrantfile which is provisioned using Ansible.
* ???
* PROFIT!!! :tada:

Ansible could even be re-used for the sys administration of dissem.in as it enables generic and reproducible deployments in carefully crafted playbooks and easy to understand.

(Disclaimer: I'm half concentrated while writing this answer due to [MCJP](mcjp.fr) that I'm following in realtime).

**Comment by wetneb** [comment]
That looks awesome! Do you think the config files for these could be derived from our travis.yml?

**Comment by RaitoBezarius** [comment]
@wetneb Definitely, I just looked and I think that the config files are somewhat anagrams of the Travis.yml :smile:

**Comment by Phyks** [comment]
@RaitoBezarius :+1: for ansible config.

**Comment by RaitoBezarius** [comment]
#261 might close this issue! :tada:

**Comment by wetneb** [comment]
Yes indeed!
