### ISSUE TITLE
Is it a bug if some CrossRef entries are missing?

### ISSUE THREAD

**Issue by cpitclaudel** [dissemin/dissemin#210]
For example,

<http://dissem.in/api/10.1007/978-3-642-18305-8> leads to

    {"message": "The paper you requested could not be found.", "error": 404}

But CrossRef knows about it (http://search.crossref.org/?q=10.1007%2F978-3-642-18305-8)

**Comment by wetneb** [comment]
Dissemin only deals with DOIs that represent papers, not books or proceedings. Concretely, we require that there is an "authors" field in CrossRef's metadata (in this DOI, there are only "editors").

I think this is a feature because a lot of what we are doing assumes we are dealing with articles. For instance, I do not think it makes sense to display the self-archiving policy of a whole volume (because I do not think editors could upload themselves the whole book to a repository). And I do not expect our sources to find a "preprint" for the whole volume.

But maybe we'd like the API to behave in a different way that the platform (and return CrossRef's metadata)?

**Comment by cpitclaudel** [comment]
Thanks for the clarification. No, I don't think the API should behave differently; that explanation makes a lot of sense. It's pretty easy to get records directly from CrossRef if they are needed, so I don't thinkit would make sense to add an extra load to Dissemin's developers.
