### ISSUE TITLE
How can I tell dissemin about an open access copy of a paper?

### ISSUE THREAD

**Issue by cpitclaudel** [dissemin/dissemin#214]
[This paper](http://dissem.in/paper/104568/) is on MIT DSpace at https://dspace.mit.edu/handle/1721.1/91993 ; how do I tell Dissemin about that? Should it just find it by itself?

**Comment by a3nm** [comment]
@wetneb, FYI, MIT DSpace seems to have an OAI-PMH interface.
https://dspace.mit.edu/oai/request

-- 
Antoine Amarilli

**Comment by cpitclaudel** [comment]
Oh, is it just that DSpace@MIT isn't indexed by Dissemin? That would explain it ^^

**Comment by wetneb** [comment]
No idea why it does not show up, I'll try to take the time to see why.

**Comment by cpitclaudel** [comment]
I seem to remember that @threonorm had a guess as to why this might happen, but I'm not entirely sure anymore.

**Comment by wetneb** [comment]
It's just because your paper has not yet made its way to BASE, hence not to dissemin. Reducing that latency would basically require us to replicate BASE's work on our side, which is not realistic.

**Comment by a3nm** [comment]
@wetneb, that said, you could still imagine that users could "tell dissemin about an open access copy of a paper", even if it hasn't made its way to BASE yet. I think we discussed this previously (though I can't find a corresponding issue), but I think ideally we would want to allow users to manually indicate open access copies of their papers, no?

**Comment by wetneb** [comment]
That's a tough question. What if they simply put a link to the PDF on
their homepage? We want to encourage proper archiving in open
repositories, don't we?
In effect, indicating an URL is all you need to deposit in Zenodo, so I
would say "depositing in Zenodo is the way to show us your paper is in OA"…

**Comment by a3nm** [comment]
I thought we were starting to consider crawling random PDFs? But even then, we could allow users to point dissemin to PDFs which (from their URLs) are in a "proper" repository (i.e., one where we know papers).

But doing it through Zenodo may be reasonable also -- it's just that the UI should then point to it so that users can indicate existing OA versions for their papers that are marked as unavaialable.

**Comment by wetneb** [comment]
Crawling random PDFs is not in my plans, I am thinking about crawling
repositories (because OAI-PMH is not enough). But some others (such as
CiteSeerX) are, and it is a good thing (they have the capacity to
archive the PDF files they find, we don't).

How would you detect if a given URL belongs to a repository we know?
