### ISSUE TITLE
Issues with ORCID: e-mail confirmation unnecessary, name changes not propagated

### ISSUE THREAD

**Issue by TedTed** [dissemin/dissemin#242]
Repro steps:
- Click on "upload" button of a paper on dissemin while logged out
- Click on "sign up", fill the ORCID form to get an account
- Once the form is filled, get redirected to dissemin in a logged-in state
- **Problem 1**: I am now considered logged in to dissemin and can upload papers; even though I didn't click on the ORCID confirmation e-mail.
- Open the ORCID confirmation e-mail and click on the confirmation link
- In ORCID, change your name (in my case, I didn't fill the last name at first and filled it afterwards).
- Log out of dissemin, log in again, go to your profile
- **Problem 2**: the name hasn't changed.

**Comment by RaitoBezarius** [comment]
So we have two issues:

- We don't check if the ORCiD profile we authenticate is confirmed or not, I think this is more related with django-allauth and his plugin for ORCiD / OAuth authentication.

- We don't propagate name changes from ORCiD to Dissemin, the reason is: we might are duplicating the names and store only the one we receive during the initial ORCiD authentication. @wetneb — I wonder how can we fix this one easily?

**Comment by wetneb** [comment]
Is it a big deal that we let unconfirmed ORCID accounts use dissemin? I see it more as a feature than a bug. If people create their account just for dissemin, then it simplifies the signup a lot. What is the value of email authentication anyway, when we can create temporary aliases easily?

The second point is an issue indeed. I guess backend.orcid should check for name changes when refreshing the papers from the ORCID profile and update accordingly?

**Comment by RaitoBezarius** [comment]
@wetneb Sounds good for the solution about name changes.
