### ISSUE TITLE
Search by name should be insensitive to accents

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#294]
Searching for "Marc Mézard" does not return anything whereas "Marc Mezard" does. @Lysxia, is this something we can fix by tweaking the search index?

**Comment by Lysxia** [comment]
We can strip accents before storing names in the index and before searching.

It's a bit simplistic, but the fact that it is the name without accents that returns some results rather than the other one suggests that a more refined solution wouldn't be effective anyway.

Should we also deal with accented titles the same way?

**Comment by wetneb** [comment]
OK. Yes I think it also makes sense for titles.

By the way, talking about titles, this is related to #199: we should
index a latex-free version of the title (but we still lack a function to
do that).
