### ISSUE TITLE
add method Paper.create_by_hal_id

### ISSUE THREAD

**Issue by monperrus** [dissemin/dissemin#316]
To interact with HAL, a method `Paper.create_by_hal_id`, similar to `create_by_doi` would be very useful.

**Comment by RaitoBezarius** [comment]
@monperrus Do you have a link (in french or english) to HAL's documentation about creating a paper by HAL identifier?

**Comment by monperrus** [comment]
I would say that the best way to do so is to retrieve and parse the
TEI-XML representation of an entry  (almost the same as the Aofr format)

https://hal.archives-ouvertes.fr/<id>/tei

eg

https://hal.archives-ouvertes.fr/hal-01089268/tei

Reference documents:

- the XSD schema:
https://github.com/CCSDForge/HAL/blob/master/schema/tei.xsd (I'm not
sure it's up-to-date)

- an introductory paper: https://hal.archives-ouvertes.fr/hal-00390966/en/

**Comment by wetneb** [comment]
One simpler way to do that would be to allow creation of `Paper` objects
by OAI-PMH identifiers (as exposed by BASE). The code would be much like
`create_by_doi` but it would use `backend.oai` instead of
`backend.crossref`.

You could then do
`Paper.create_by_oai_id('ftartxiker:oai:HAL:halshs-01080175v1')`.

**Comment by monperrus** [comment]
Excellent!

**Comment by wetneb** [comment]
@monperrus you'll have to configure dissemin with a proaixy API key as this feature relies on our internal OAI proxy. We can give you one by email.

**Comment by monperrus** [comment]
Good to know.

> you'll have to configure dissemin with a proaixy API
What is this?

> relies on our internal OAI proxy.
Why is this required?

**Comment by wetneb** [comment]
Proaixy is our internal OAI-PMH cache of BASE (which includes HAL). Using an OAI-PMH proxy reduces the load on our upstream metadata sources. This OAI-PMH proxy is protected by access keys, because we are not allowed to redistribute BASE's OAI-PMH data to anyone.
Note that it is also possible to use dissemin with other OAI-PMH endpoints, such as HAL's own OAI-PMH endpoint, by configuring an OaiPaperSource with the endpoint you want to use.

**Comment by monperrus** [comment]
OK, thanks for the explanation.

> it is also possible to use dissemin with other OAI-PMH endpoints, such
> as HAL's own OAI-PMH endpoint, by configuring an OaiPaperSource with
> the endpoint you want to use.
This is what I want to do. How to this in addition to `p =
Paper.create_by_hal_id('hal-00830421')`?

**Comment by wetneb** [comment]
This should work:
<pre>
from backend.oai import OaiPaperSource, CustomSourceOAIDCTranslator

from papers.models import OaiSource
hal = OaiSource.objects.get(identifier='hal')
s = OaiPaperSource('https://api.archives-ouvertes.fr/oai/hal/')
s.add_translator(CustomSourceOAIDCTranslator())
p = s.create_paper_by_identifier('oai:HAL:hal-01164591v1', 'oai_dc')
p.save()
</pre>
