### ISSUE TITLE
UBlock breaks ORCID login

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#319]
UBlock blocks https://orcid.org/oauth/custom/login.json, so users cannot login via ORCID.

**Comment by a3nm** [comment]
I said something silly, the request to https://orcid.org/oauth/custom/login.json appears in the uBlock log but does not appear to be blocked. After some investigation, the reason why this fails is because uBlock blocks https://www.google-analytics.com/analytics.js. Now, when clicking the login button, ORCID runs the submitLogin() function in [angularOrcid.js](https://3ee18a8e3b5f36cc534e-e1e82d2ad70a9388a1453137f78c6701.ssl.cf1.rackcdn.com/javascript/angularOrcid.js?v=2016-10-13T20:15:08Z):10104. This function (on line 132), in a callback when the login succeeds, calls orcidGA.windowLocationHrefDelay(data.redirectUrl) defined in [script.js](https://3ee18a8e3b5f36cc534e-e1e82d2ad70a9388a1453137f78c6701.ssl.cf1.rackcdn.com/javascript/script.js?v=2016-10-13T20:15:08Z):192 which essentially makes a call to Google Analytics (which is blocked) with a callback to redirect the user to the right page after login.

So what happens, I think, is that the login works perfectly except the last step of actually redirecting after login.

So I think this should be bugreported to ORCID by asking them to fix their code so that login also works even when calls to Google Analytics are being blocked (i.e., they should do the setTimeout on script.js:195 no matter what). Arguably this could also be fixed on the uBlock side, e.g., instead of blocking Google Analytics call they could intercept them and execute the callbacks as if they had succeeded, but I think that's way more involved than the blocking they usually do, and they wouldn't want to go that route.

**Comment by wetneb** [comment]
Issue reported to ORCID.

**Comment by wetneb** [comment]
It seems that their fix has made its way to production as I cannot reproduce this anymore.
