### ISSUE TITLE
Misclassification of papers (issue at ORCID?)

### ISSUE THREAD

**Issue by corinalogan** [dissemin/dissemin#338]
I looked up my papers at dissem.in (using my ORCID: 0000-0002-5944-906X) and many are not listed as being available even though all of my papers are in a repository (in some form) and also at my website. For dissem.in to be informative, it seems like it would take a bit of work to get it to accurately reflect the availability of my publications. 

Perhaps I have mis-entered something at ORCID, which is why my dissem.in record is off? Or maybe it is the Apollo repository (the University of Cambridge repository where most of my papers are) that ORCID and dissem.in are having trouble interfacing with? It would be good to know how I can fix this (e.g., if dissem.in or ORCID gave instructions on how to make papers in repositories appear as being available for download). If dissem.in is accurate, then I think it can help researchers make their products open if there are instructions on how to do this (for now, the website says to email them and they will fix the problem: http://dissem.in/faq#availability).

**Comment by wetneb** [comment]
Hi @corinalogan, thanks very much for your feedback! We are aware that the availability of papers is currently very inaccurate. We are working on the issue and hope to release a new version soon that should be much better in this regard (and many others!).
Best regards,
Antonin

**Comment by sje30** [comment]
hi @wetneb thanks for following up.  Corina is also at Cambridge, and we would love to get more people using your tool in the new year...

**Comment by corinalogan** [comment]
Hi @wetneb, 
Thanks so much for keeping this on your radar! I'd love to learn if I'm doing something wrong at ORCID so do let me know how you end up resolving this issue. As @sje30 says, we would really like to start promoting dissem.in as a tool to help people make all of their products freely available online.
My best,
Corina

**Comment by wetneb** [comment]
@corinalogan You're not doing anything wrong in your ORCID profile. By definition, users are right! The issue comes from the fact that the Cambridge repo does not currently expose its metadata in a way that makes [BASE](http://www.base-search.net/) (hence dissemin) recognize full texts there. The repository managers are aware of this issue.

For instance, on papers like this one: http://dissem.in/p/258552/how-new-caledonian-crows-solve-novel-foraging-problems-and-what-it-means-for-cumulative-culture , dissemin detects that the paper is present in the repo, but is not sure if the paper can be downloaded for free from there.

In the new version, we will not rely on BASE's availability detection, and this problem should be solved. Alternatively, this might be solved earlier if Cambridge's repo complies with the european guidelines:
https://guidelines.openaire.eu/en/latest/data/index.html
but with the coming brexit I understand that this is not really a priority…

**Comment by corinalogan** [comment]
@wetneb Ah, ok, this makes sense, thank you for explaining it to me. I'll send your message to the people who work with the repository in case they are not aware of this issue. I know they are very open to feedback so hopefully they might fix this issue sooner rather than later. Thanks again!

**Comment by wetneb** [comment]
As far as I know, they are aware of the issue, as I talked to D. Kingsley about that at OpenCon last year. Not sure it is worth bothering them with it again :-)

**Comment by sje30** [comment]
If it has been a year then we should remind them!

On 18 December 2016 17:56:24 GMT+00:00, Antonin Delpeuch <notifications@github.com> wrote:
>As far as I know, they are aware of the issue, as I talked to D.
>Kingsley about that at OpenCon last year. Not sure it is worth
>bothering them with it again :-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dissemin/dissemin/issues/338#issuecomment-267835813

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by corinalogan** [comment]
@sje30 I sent them a note :)

**Comment by sje30** [comment]
hi @corinalogan do we need to remind them again?

**Comment by corinalogan** [comment]
Hi @sje30,
I emailed them on 3 Jan and they forwarded my email to "Peter Sutton-Long, our Repository Manager, and Agustina Martinez, our Repository Integration Manager". I haven't heard anything from them since then, but I'm not sure if I would unless they followed up to let me know it was fixed.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
