### ISSUE TITLE
False negative for some Wiley journals' policies

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#432]
I have some 1516 DOIs from ANIE like https://dissem.in/api/10.1002/anie.196701792 which are classified as UNK despite it's a ROMEO yellow journal: http://www.sherpa.ac.uk/romeo/search.php?issn=1433-7851

Perhaps you're missing the ROMEO record because it uses the title "Angewandte Chemie International Edition" without "in English" at the end? I cannot see any other mismatch.

**Comment by wetneb** [comment]
That is probably a caching problem, I suspect the policy has been updated since it was first fetched by dissemin.

**Comment by nemobis** [comment]
Really? RoMEO says last updated in August 2014. I just got a couple RoMEO entries updated by the way, I'd be interested in knowing how frequently you fetch updates.

**Comment by wetneb** [comment]
I will investigate!
Our Romeo cache expires after a few months if I remember correctly - their API is quite unstable so I have put a fairly aggressive cache. Ideally it should be possible to refresh policies manually.

**Comment by a3nm** [comment]
OK so here are some notes from an investigation of this. Dissemin obtains SHERPA/RoMEO information from a cache, romeo-cache.dissem.in, which runs [this code](https://github.com/dissemin/romeo_cache). This cache is supposed to make entries expire after 3 months (see `record_life` in `cache/views.py` in this code), and it seems to do the job correctly.

The problem is that Dissemin stores publisher and journal information in its database when retrieving it from the cache and never updates it anymore. This is happening in `fetch_journal` and `fetch_publisher`. At a high level, the database should first be modified to store when these kinds of objects have been retrieved, and the code changed to store this info. Then the code should be changed to say that when the object that we retrieve from the database is too old, then it should be updated with information that was fetched from romeo-cache.

**Comment by Phyks** [comment]
Likely to be solved by ongoing work on ROMEO (#623 #614).

**Comment by wetneb** [comment]
Thanks, this is indeed solved now, the policy has been updated. \o/
