### ISSUE TITLE
Change default license selection for Zenodo

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#441]
When I click the upload button and Zenodo is selected, "Other open license" is selected by default. This is not helpful, cf. https://www.gnu.org/licenses/license-list.html#which-cc

I suggest to select CC-BY-SA or CC-BY by default. If the author does not actually have the right to use such license, e.g. because the journal policy mandates the use of CC-BY-NC, the license will automatically degrade itself to whichever license is acceptable (article 8b https://creativecommons.org/licenses/by-sa/4.0/legalcode ).

**Comment by wetneb** [comment]
@nemobis the rationale behind this choice was that we did not want to auto-select an option that actually bears some meaning without the user's explicit consent.

But your point about article 8b sounds very interesting, and I would be in favor of updating the default choice in that regard.

Feel free to propose a PR. All you need is to change the following line:
https://github.com/dissemin/dissemin/blob/14315c8ef905d2b8bb857e122ce1825c7e970f3f/deposit/zenodo/forms.py#L47

**Comment by a3nm** [comment]
I'm not a lawyer but I worry that your interpretation of article 8b may
be too generous. If I'm not mistaken, article 8b is just a severability
clause <https://en.wikipedia.org/wiki/Severability#Sample_clause> which
is standard legal boilerplate found in all sorts of contracts (not just
copyright licenses).

In fact, I think that if you have signed away your copyright on some
work to a publisher, then it is not a good idea to license this work
under a CC license, because it amounts to granting rights that legally
you no longer have. This is implicit in
<https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees#Clear_rights_needed_to_use_the_material.>
and
<https://creativecommons.org/faq/#can-i-use-a-creative-commons-license-if-i-am-a-member-of-a-collecting-society>.

The clearest reason why you shouldn't do this is as follows: author X
claims that the work is under a CC license even though X no longer owns
the copyright; PDF aggregator Y downloads the paper and redistributes
it, pursuant to the CC license; publisher Z attacks Y because they
infringed on their copyright, and Y is screwed. :( I'm not sure of what
are the implications for X: maybe Y can sue X because of the invalid
license, maybe Z can sue X directly for making false claims about the
work because they own the copyright.

[Aside: I think that it would be very nice to have a way to say what you
propose, i.e., "as far as I'm concerned this work is under CC, but I'm
not positive that no one else owns the right now, so if you want to
reuse the material it's up to you to do the homework and face the legal
risks". However I don't know of a standard way to do this.]

I understand that it's annoying to make non-CC the default, because it's
better if people license their works under CC, but I agree with Antonin
that it's a bad idea to make people say "my work is under CC" without
knowing if they can legally do so and without requiring explicit action
on their part. Specifically: if we know that the work was published with
a publisher which is not OA-friendly (requires transfer of copyright and
does not allow licensing the work under CC), then we shouldn't make
users do it by default, because for all we know they probably don't have
the right to do it.

**Comment by nemobis** [comment]
a3nm, 27/08/2017 16:12:
> In fact, I think that if you have signed away your copyright on some
> work to a publisher, then it is not a good idea to license this work [...]

Sure, the problem is that that "if" is very hard to verify given the 
jungle of contracts and policies. Most publishers allow to license the 
pre-print at least, and it's a very good idea to take this opportunity.

I'm not strongly advocating for a specific license; you can inquire 
Creative Commons for some advice on the implications of specific 
provisions in this context.

What I really dislike is the misleading nature of an option like "other 
open license", especially when selected by default: it's pure nonsense 
if one doesn't state *which* license, and it tricks authors into 
thinking they made their work "open" (copyright-wise) when they didn't. 
This option makes sense only if the license is different from the 
previously listed ones *and* is stated in the PDF itself, which almost 
never happens.

The "other open license" option should not exist at all (it's of 
negligible usefulness) or should be a text field requiring input of a 
license URL.

Federico

**Comment by wetneb** [comment]
@nemobis here is the list of available licenses, if you want to suggest a better one for the default choice:
http://pintoch.ulminfo.fr/4fb33971d3/licenses.tsv

**Comment by nemobis** [comment]
Antonin Delpeuch, 27/08/2017 17:33:
> @nemobis <https://github.com/nemobis> here is the list of available 
> licenses, if you want to suggest a better one for the default choice:
> http://pintoch.ulminfo.fr/4fb33971d3/licenses.tsv

Thanks. I've reviewed the list and I don't see any suitable option: 
they're either licenses for code or data or very obscure licenses, 
except the Free Art License which is a decent one.

Concerns about applicability of CC-BY or CC-BY-SA would not be solved by 
any OSI-approved license and even less by strong copyleft or pseudo-CC0 
licenses. You could shoot for CC-ND hoping nobody would be annoyed by 
it, but that would not be a legal consideration.

The only copyright statement which circumvents the question of whether 
the author is able to license a work is one that is not a license; for 
instance <http://rightsstatements.org/page/InC-EDU/1.0/>.

Federico

**Comment by a3nm** [comment]
I agree that "other open license" makes little sense. If we don't want to encourage authors to claim to license their works in a risky way, I think the default should be the least permissive, i.e., I guess, zenodo-freetoread-1.0: "Free for private use; right holder retains other rights, including distribution".

I agree that this sucks, but I don't know what else can we do: personally I do this on arXiv for my own papers when they are covered by a copyright agreement (i.e., I select the arXiv license that says "can be distributed on arXiv and that's all"), because I don't know a better option.

Arguably, we could be bolder specifically for preprints, but I don't know many publishers who specifically waive any claim of rights to the preprint, and barring this I'm not sure I understand the legal status of preprints: when you give away copyright on a derivative work, do you retain copyright on the initial work? Because I don't understand this, I don't feel comfortable licensing a preprint under a Creative Commons license when a copyright transfer has been signed for the final paper.

For this kind of reasons I think it would be better to switch to zenodo-freetoread-1.0, even though, yeah, it sucks that we can't encourage people to deposit under an open license by default. :/

**Comment by nemobis** [comment]
a3nm, 29/08/2017 18:52:
> For this kind of reasons I think it would be better to switch to 
> zenodo-freetoread-1.0, even though, yeah, it sucks that we can't 
> encourage people to deposit under an open license by default. :/

Indeed. I'd still try to ask CC about article 8b. If you want to talk 
with SHERPA/RoMEO about this and they're open in principle to adding 
information about "libre OA" policies (i.e. whether CC-BY is allowed), I 
could volunteer to populate it by reading, let's say, the 100 most 
important publisher's/journal's polcies to start with.

**Comment by a3nm** [comment]
On Tue, Aug 29, 2017 at 09:12:13PM +0000, nemobis wrote:
> Indeed. I'd still try to ask CC about article 8b.

I'm reasonably confident that this is just a severability clause and
that it does not imply that it's OK to put your work under a CC license
if you don't know whether you legally can. However, if you can get in
touch with them, it will always be interesting to know what they say.
More generally, I wonder whether they know an answer to my question: how
can I say that my work is under CC as far as I'm concerned but that it's
the reuser's job to clear the rights if they want to do something
serious with the work.

> If you want to talk with SHERPA/RoMEO about this and they're open in
> principle to adding information about "libre OA" policies (i.e.
> whether CC-BY is allowed), I could volunteer to populate it by
> reading, let's say, the 100 most important publisher's/journal's
> polcies to start with.

I agree it would make sense in principle for SHERPA/RoMEO to have this
kind of data, but I don't know what it would look like in terms of
coverage. In my field the important publishers are ACM, IEEE, Springer,
Elsevier; and to my knowledge, none of them explicitly permit CC
licensing on the preprint or on the postprint. The only CC-friendly
publishers I know are the diamond ones (Schloss Dagstuhl, Episciences,
etc.) who publish the final version under a CC license themselves.

Best,

-- 
Antoine Amarilli

**Comment by nemobis** [comment]
a3nm, 30/08/2017 02:08:
> it does not imply that it's OK to put your work under a CC license
> if you don't know whether you legally can. 

There is a difference between knowing you can't and not knowing you can.

Anyway, the result for Dissemin is the same because we should not 
encourage people to do something they might not be able or want to do 
and stick to. Let's change to the non-license now and hope people will 
think about selecting a license when they believe they could.

> I agree it would make sense in principle for SHERPA/RoMEO to have this
> kind of data, but I don't know what it would look like in terms of
> coverage.

They already have quite many journals with some information on the 
matter, but it's not structured:
<https://www.google.com/search?q="Creative+Commons"+site%3Ahttp%3A%2F%2Fwww.sherpa.ac.uk%2Fromeo%2Fissn%2F>

**Comment by a3nm** [comment]
On Tue, Aug 29, 2017 at 11:07:44PM -0700, nemobis wrote:
> a3nm, 30/08/2017 02:08:
> > it does not imply that it's OK to put your work under a CC license
> > if you don't know whether you legally can. 
> 
> There is a difference between knowing you can't and not knowing you can.
> 
> Anyway, the result for Dissemin is the same because we should not 
> encourage people to do something they might not be able or want to do 
> and stick to. Let's change to the non-license now and hope people will 
> think about selecting a license when they believe they could.

Agreed.

> > I agree it would make sense in principle for SHERPA/RoMEO to have this
> > kind of data, but I don't know what it would look like in terms of
> > coverage.
> 
> They already have quite many journals with some information on the 
> matter, but it's not structured:
> <https://www.google.com/search?q="Creative+Commons"+site%3Ahttp%3A%2F%2Fwww.sherpa.ac.uk%2Fromeo%2Fissn%2F>

Yeah, but looking at these records, in many cases the Creative Commons
indication talks about the license of the content on the publisher
website. I haven't seen an example yet where a publisher allowed authors
to archive under a CC license without distributing themselves the
material under that license.

That said, the license of the content on the publisher website is also
important information that should be in SHERPA/RoMEO... but it's
distinct from the question of which licenses are permitted for
self-archiving.

Best,

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
closing as no consensus was reached, feel free to reopen / submit a PR to change things if you disagree.

**Comment by nemobis** [comment]
I hope I've not blocked a resolution! I'm fine with a3nm's proposal of zenodo-freetoread-1.0.

Other options may make sense in the future if the uploaders become able to edit the Zenodo records to e.g. add license statement files.

**Comment by wetneb** [comment]
Although "zenodo-freetoread-1.0" is available in Zenodo's model:
https://zenodo.org/api/licenses/zenodo-freetoread-1.0
it's not actually proposed by the auto-completion dialog in the UI when creating an open deposit, and it is refused by the API. So we cannot use that.

**Comment by a3nm** [comment]
Thanks a lot, @wetneb, for taking care of this long-standing task! :)
