### ISSUE TITLE
DOI redirect does not work with URL-encoded DOI

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#517]
This gives a page not found:
https://dissem.in/10.1175%2F1520-0426%282003%29020%3C0383%3ARCAACO%3E2.0.CO%3B2

But the original DOI is hard to link:
https://dissem.in/10.1175/1520-0426(2003)020<0383%3ARCAACO>2.0.CO%3B2

The workaround is to use `/` instead of the first `%2F`, so that the rewrite comes into action. Maybe this format could be recognised as well.

**Comment by Phyks** [comment]
Hi,

http://localhost:8080/10.1175%2F1520-0426%282003%29020%3C0383%3ARCAACO%3E2.0.CO%3B2

works in the Vagrant (dev) VM. So this is not a dissemin code base issue. I see two possible explanations here: 

* Either this has been fixed recently in the code base and the issue was not closed.
* Or this is coming from a particular setup in production. My wild guess would be that this could be coming from a reverse proxy or WSGI setup, as the dev VM is working and makes use of Django's internal webserver.

@wetneb could you check the logs in production for this error?

**Comment by wetneb** [comment]
I can confirm that the problem disappears when running a Django webserver from the production instance, so indeed this must have something to do with Apache or the WSGI configuration. Not sure how to debug that - maybe Django's webserver does the unescaping by itself and we can just add this unescaping in our own code.
