### ISSUE TITLE
Clickable regions on the deposit page

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#657]
On the deposit page:

- [x] Clicking the description of a repository should select the radio button for that repository
- [x] Clicking the title bar of a panel should expand/collapse it (not just the text in the title bar)

**Comment by Phyks** [comment]
Also, at first load of the deposit form, there is no default selection for the type of deposit, see
<img width="689" alt="Capture d’écran 2019-03-26 à 17 36 52" src="https://user-images.githubusercontent.com/3856586/55015813-d7549980-4fed-11e9-9f53-dcf391fe35f8.png">

Should not there be a default option? (probably preprint is the safest option)


And

- [ ] Deposit button should be greyed out until all required fields are filled in.

**Comment by wetneb** [comment]
There is a default selection if you came from the paper page and clicked one of the options already. Otherwise I would be reluctant to add a default one - the idea with the current set up is that making the user choose between one of these three versions ensures that they are aware of the publisher policy for that version.

**Comment by Phyks** [comment]
Oh, I missed that. It definitely makes sense. Thanks

**Comment by wetneb** [comment]
But yeah for the greyed out button it totally makes sense. Also at the moment we are not scrolling back up to the missing required field if they hit the button, which is confusing (for instance the file upload field is often too high enough to be seen).
