### ISSUE TITLE
Paper list mixes authors with iD and without iD badge, should explain better

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#660]
For instance with https://dissem.in/search/?authors=antoine+amarilli, "Antoine Amarilli" sometimes appear with an iD badge (paper linked with the ORCID profile) and sometimes does not (when this is not the case).

It might be troubling for new comers and not clear what this badge means. A minimal and easy fix could be to add a title on the iD badge to describe what this means when the iD badge is here.

**Comment by a3nm** [comment]
I agree that's a bit confusing. At least a tooltip can't hurt. As for having some text, I'm not sure... "Linked to Orcid"?

Another point is that I'm not sure it's a good idea to have this icon point to Orcid rather than to the profile of the researcher on Dissemin. I understand the intention but I think it's confusing to users who really have no reason to want to get to an Orcid profile by clicking there.

**Comment by wetneb** [comment]
Yes, we could absolutely link that iD badge like the rest of the link (to https://dissem.in/<orcid> or the /r/<pk> page if the profile is already fetched).
