### ISSUE TITLE
Enable warnings of INFO logging messages in console

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#673]
Hi @beckstefan,

The logging set up works great! However, it seems that there is no simple way to run a Python shell with a specified log level. When running an import, I generally want to see all the `INFO` level messages, for instance. So I would advocate that we either change this default logging level in the configuration, or find a way to add the logging level as a parameter of the Python shell (such as `./manage.py shell -l INFO`). What do you think?

**Comment by beckstefan** [comment]
I intentionally set up logging to log default `INFO` or higher in production. However I did a stupid mistake:

1. I used `DEBUG` for production
2. I wrote `DEBUG` and not `"DEBUG"`, so logging for dissemin gets disabled.

I'll fix that with a PR shortly.

If that wasn't the issue, i.e. you corrected my errors, you should check your apache log settings, that it does not filter `INFO`. Logging in Python is flexible. You could redirect everything from dissemin into a separate file or just from some modules by adding new loggers and handlers for your production setup.

I'll also provide an option to pass LOGLEVEL via `./mangage shell` by using environment variables and add some documentation.

Since we're on topic: How is Sentry doing with the logging?

**Comment by wetneb** [comment]
At the moment I think Sentry reports all log messages with warning level or higher. I think that's appropriate (we might need a bit of tuning to turn some WARNING into INFOs though).

**Comment by wetneb** [comment]
Fixed by #675.
