### ISSUE TITLE
ORCID as a paper source?!

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#726]
In the output for this paper https://dissem.in/api/10.4230/lipics.icdt.2018.6 the first source given is a link to an ORCID profile. I'm not sure what is the point? If a paper is listed in someone's ORCID profile, it doesn't mean that the paper is actually made available there, does it?

**Comment by wetneb** [comment]
The point is to track the *provenance* of the metadata! Since we are able to import paper metadata from ORCID (where no other external identifier might be available), we need to keep track that the metadata is coming from there. As you rightly point out, ORCID does not host full texts, hence the `pdf_url` for these OaiRecord will always be null.

The meaning of `splash_url`, in general, is to point to any webpage where the paper is described. For instance, many papers are described in HAL without the full text being available from there: this is another example of case where OaiRecord will point to the website in `splash_url`, but have a null `pdf_url`.

If you do not want to see these ORCID links at all, then there will be many papers where it will not be possible to tell where Dissemin got its metadata from: many papers will have no external link whatsoever.

**Comment by a3nm** [comment]
Ah OK I see, this makes sense. @PierreSenellart 's use case is that when Dissemin has no `pdf_url` he wanted to link to the first `splash_url` in the hope that this is a publisher link, i.e., where the paper may be available behind a paywall. So ideally one could distinguish between "a place where the paper is described (without being available)" (e.g., a HAL page with no deposit, an ORCID page) and "a place where the paper is available behind a paywall".

In fact @PierreSenellart I guess a better fallback (if there is no `pdf_url`) is to link to the standard DOI resolver link (assuming the DOI is known), which will usually redirect to the publisher webpage?

Meanwhile let me add what you said to the documentation and close the issue.
