### ISSUE TITLE
List of papers by ORCID author is incomplete

### ISSUE THREAD

**Issue by fxcoudert** [dissemin/dissemin#730]
If I search for papers by a valid ORCID author id (for example [0000-0001-5318-3910](https://orcid.org/0000-0001-5318-3910)), not all papers known to ORCID are found by dissemin: 85 papers founds, while the ORCID list has 109. No reason is indicated for this discrepancy.

**Comment by wetneb** [comment]
Thanks for the report! In theory there should be some notifications about these missing papers, but apparently this is not working as expected.

**Comment by Phyks** [comment]
There is a notification message down the list of papers:

![Capture d’écran 2019-04-23 à 11 45 30](https://user-images.githubusercontent.com/3856586/56571474-545b3a80-65bd-11e9-99f9-7bca8166dd3b.png)

Maybe we should emphasize it a bit more?

Maybe this is related to https://github.com/dissemin/dissemin/issues/659 as well?

**Comment by Phyks** [comment]
I had a deeper look into this issue. Here is a set of two list of publications (titles only), aligned one with another (so that differences can be found quickly): https://gist.github.com/Phyks/0685dc25be4e38780578923aae44c51d (`orcid.txt` is the list coming from the ORCID profile, `dissemin.txt` is what Dissem.in currently exposes).

I skimmed quickly through it:

* Some papers sound like duplicates on the ORCID side. This accounts for a few differences. For instance, "Computational characterization and prediction of metal-organic framework properties" is twice in the ORCID profile.
* But there is also a real issue here in Dissemin since some real papers *are* not imported/exposed in the Dissemin ORCID profile.

Focusing on these import errors, I found "Flexibility and disorder in metal-organic frameworks" (https://doi.org/10.1039/c6dt90026g) for instance. It is actually imported in Dissemin (https://dissem.in/p/54768119/flexibility-and-disorder-in-metalorganic-frameworks), with the correct ORCID badge associated with @fxcoudert! Then, it looks like a display / indexing issue. I'll have a look why this is never shown in the ORCID profile page.

@fxcoudert Please, let me know if you don't want such a list to be available publicly, I will make it private.


For the records, for similar issues in the future, here is how I got this list:
```
curl -H "Accept: application/orcid+json" "https://pub.orcid.org/v2.1/${ORCID}" | jq '."activities-summary".works.group[]."work-summary"[].title.title.value' | sort | uniq > orcid.txt
for PAGE in 1 3; do
    curl "https://dissem.in/api/r/${RESEARCHER_ID}/${RESEARCHER_SLUG}?page=${PAGE}" | jq '.papers[].title' >> api_dissemin.txt
endfor
cat api_dissemin.txt | sort | uniq > dissemin.txt
```
And then I used Meld to align them one with another.

**Comment by fxcoudert** [comment]
@Phyks no problem, the list is publicly available already :)

For what it's worth, ORCID has a simple API and I use it from Python with:

```
api = orcid.PublicAPI(identifier, secret)
token = api.get_search_token_from_orcid()

record = api.read_record_public(sys.argv[1], 'record', token)
print(f'ORCID: {record["orcid-identifier"]["path"]}')
name = record['person']['name']
print(f'Name: {name["given-names"]["value"]} {name["family-name"]["value"]}')

works = api.read_record_public(sys.argv[1], 'works', token)['group']
print(f'Number of papers in ORCID: {len(works)}')

dois = []
for paper in works:
    doi = findDOI(paper)
    if doi:
        dois.append(doi)
    else:
        title = paper['work-summary'][0]['title']['title']['value']
        print(f'No DOI available for paper: {title}')

print(f'Number of papers with DOI: {len(dois)}')
```

**Comment by Phyks** [comment]
@wetneb Importing `0000-0001-5318-3910` locally in a VM, I get 109 fetched papers (on `master` branch), which is fine. However, a refresh on dissem.in only yields 52 papers.

There seems to be something bad happening in production, outside of the code base (or a bad interaction between multiple sources). Any idea?

**Comment by wetneb** [comment]
@fxcoudert thanks again for reporting this important bug. It is now solved.
