### ISSUE TITLE
Paper disappeared from profile and search results after being submitted to HAL

### ISSUE THREAD

**Issue by PierreSenellart** [dissemin/dissemin#765]
Consider the following article:
https://dissem.in/p/102423133/regularized-cost-model-oblivious-database-tuning-with-reinforcement-learning

It used to be part of my profile on Dissemin. I deposited it to HAL. It is now not visible on my profile anymore, and it does not even appear when searching for my name:
https://dissem.in/search/?authors=pierre+senellart

Any idea why?

**Comment by Phyks** [comment]
When going to [the paper page](https://dissem.in/p/102423133/regularized-cost-model-oblivious-database-tuning-with-reinforcement-learning), your name still appears with an ORCID badge next to it, so in principle, it should be fine in your profile.

This error might be another instance of #730 and related issues, which should be solved by a PR @wetneb merged yesterday. A new ElasticSearch index is currently being built, hopefully this will be fixed in 10 days when the new index is ready.

**Comment by wetneb** [comment]
Yes, this was the same issue and it is now solved.
