### ISSUE TITLE
After using advanced search with only restriction pubdate_before pagination does not work 

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#817]
When going to advanced search, select Pubdate before, select e.g. today, then hit search, results load fine.

Using then pagination, loads results but then redirects to the results of page 1.

Maybe other search fields are concerned, too.

**Comment by Phyks** [comment]
This is because, upon entering the search results page, `/ajax/search` API endpoint is called. This should not happen and it should only be called when actually editing the search fields (for live filtering). Not sure why this is happening, I'm wondering whether this is not a recent regression.

I'll try to have a look ASAP.

**Comment by beckstefan** [comment]
I suspect that this is caused by DateTimePicker / Tempus Dominus.

I cannot reproduce this, when using other fields, however, I can reproduce it if I combinee any field with PubDate.

My explanation is as follows:
We use an `onChange` trigger event. For some reason the pagination link does trigger something on named packages, so that they trigger an `onChange` evnt and consequently AJAX gets into action. Maybe this has something to do with prefilling the field.

For BS4 I removed onChange for now, which solves this behaviour. In my opinion, the only downside is, that the user must hit the enter button on keyboard or the search button. But the differences from deselecting is rather minimal.

**Comment by beckstefan** [comment]
Closed by #839
